#!/bin/sh

include () {
    cp -rf $1 ${clear}
}

main () {
    rm -rf ${clear}
    mkdir -p ${clear}
    include ~/.ssh
    include ~/.aws
    include ~/.hub
    zip -e -r credentials ${clear}
    rm -rf ${clear}
}

clear=./credentials
main
