#!/bin/sh
./decrypt
for ii in $(ls -A ./credentials); do
    cp -r ./credentials/$ii ~
done

ssh-add

rm -rf ~/MB.new
git clone git@github.com:bryanhann/clear

cd ~/clear

echo ENTERING SHELL
bash --norc
echo LEAVING SHELL

