#!/bin/sh

[ "$0" = "./install" ] || echo "try './install'"
[ "$0" = "./install" ] || exit 99

./decrypt

for ii in $(ls -A ./credentials); do
    cp -r ./credentials/$ii ~
done

ssh-add

export ARF_HOME=${HOME}/.arf
mkdir -p ${ARF_HOME}

src=git@github.com:bryanhann/arf
dst=${ARF_HOME}/arf

git clone ${src} ${dst}

