#!/bin/sh

[ "$0" = "./shadow-install" ] || echo "try './shadow-install'"
[ "$0" = "./shadow-install" ] || exit 99

echo ++ [$0] [$*]

./decrypt

for ii in $(ls -A ./credentials); do
    cp -r ./credentials/$ii ~
done

ssh-add

./myborg-install



#echo
#export ARF_HOME=${HOME}/.arf
#mkdir -p ${ARF_HOME}
#src=git@github.com:bryanhann/arf
#dst=${ARF_HOME}/arf
#rm -rf ${dst}
#git clone ${src} ${dst}
#cd ${dst}
#echo -- [$0] [$1]

##./install $*

echo END $0
